### ISSUE TITLE
Integrate with Elastos Carrier

### ISSUE THREAD

**Issue by liyangwood** [cyber-republic/elastos-ReactNative-framework#1]
https://github.com/elastos/Elastos.NET.Carrier.iOS.SDK
build ElastosCarrier.framework and import to this project.

**Comment by liyangwood** [comment]
there is temporary stop due to the dylib issue for carrier ios sdk. 
will restart it when carrier team fix the dylib issue.

**Comment by jmsaulnier** [comment]
@liyangwood Thanks for sharing this issue. Are you planning to create a new repo like react-native-elastos-carrier ?

**Comment by kpachhai** [comment]
Everything that has to do with react native will live in this repo. Check the branch. There’s already a branch for elastos carrier plugin. We have our first weekly meeting for this project tomorrow and we will start this project officially. We have around 7 people who have decided to help us on this project.

**Comment by jmsaulnier** [comment]
@kpachhai for now it's fine to have a monolithic repo but when we have a stable version it would be good to decouple some parts 🔨

**Comment by kpachhai** [comment]
The reason it's in in this same repo is because we're writing react native plugins for carrier, wallet, DID, etc so it doesn't make sense to have them live on separate repos as they'll all need to be part of this same framework we're building.

**Comment by tomsej** [comment]
@kpachhai @liyangwood @mukulverm4 seems that the PR is merged and there is CR folder (not ideal name btw). What is the state of this issue? Can we close it?

**Comment by liyangwood** [comment]
Already get the solution to integrate carrier to RN app. 
so close the issue.
