### ISSUE TITLE
Docker related issues while starting proxy [SOLVED]

### ISSUE THREAD

**Issue by ademcan** [cyber-republic/elastos-ReactNative-framework#10]
If you encounter docker related issues when running "npm run dep:start" such as:
ImportError: No module named 'docker.types'
ImportError: cannot import name 'IPAMConfig'
...

The following commands solve them in my case:
pip uninstall docker
pip uninstall docker-py
pip uninstall docker-compose
pip install docker
pip install docker-compose

**Comment by kpachhai** [comment]
Thanks for bringing this issue up. I myself didn't have any issue but good to know.

**Comment by leonjq** [comment]
pip uninstall docker-compose
curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
chmod +x /usr/local/bin/docker-compose && \
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose && \
docker-compose --version

The advantage of this is that only docker-compose has been upgraded, and no changes have been made to other python pip installations. Docker-compose works fine.
