### ISSUE TITLE
Double Conversion Build Error for iOS, error: Build input file cannot be found

### ISSUE THREAD

**Issue by waynetogo** [cyber-republic/elastos-ReactNative-framework#18]
```
:-1: Build input file cannot be found: '/Users/chiawenyang/elastos-ReactNative-framework/node_modules/react-native/third-party/double-conversion-1.1.5/src/diy-fp.cc'

:-1: Build input file cannot be found: '/Users/chiawenyang/elastos-ReactNative-framework/node_modules/react-native/third-party/double-conversion-1.1.5/src/cached-powers.cc'

:-1: Build input file cannot be found: '/Users/chiawenyang/elastos-ReactNative-framework/node_modules/react-native/third-party/double-conversion-1.1.5/src/bignum.cc'

:-1: Build input file cannot be found: '/Users/chiawenyang/elastos-ReactNative-framework/node_modules/react-native/third-party/double-conversion-1.1.5/src/double-conversion.cc'
```

Build error when cloning the master and carrier source from the GitHub repository.

Solution is to in Finder, drag and copy the /elastos-ReactNative-framework/node_modules/react-native/third-party/double-conversion-1.1.5/ folder to Xcode ELASTOS_RN_FRAMEWORK/Libraries/React.xcodeproj/ThirdParty/

**Comment by waynetogo** [comment]
![double conversion error](https://user-images.githubusercontent.com/6621128/47250805-274f8480-d3ee-11e8-91d3-099fdc547bbf.jpeg)

**Comment by kpachhai** [comment]
Let's use the labels. I have added the label "bug" to this issue.

**Comment by liyangwood** [comment]
That is wired. for my side. when start to run the app with click the run button in xcode. the RN server will running automatically. but android studio not. I need to start RN server by command and run the app.

my xode is Version 10.0 (10A255)
what about you guys?

**Comment by ademcan** [comment]
Yes, it is also the case for most of my RN related apps.
However, in this case it was not starting by itself, I am also not completely sure that this is the reason of the error...
I have the same Xcode version 10.0 (10A255).

**Comment by ademcan** [comment]
Ok, so now it works... Xcode can start the node server by itself.
What happened before is that I was also having the double conversion issue before Xcode can start the node server, then I was just starting the node server manually and building with Xcode to fix. It seems that once it is fixed Xcode manages itself to start the server (which is the way it should be).

**Comment by liyangwood** [comment]
@waynetogo please verify this issue and close it if it works.

**Comment by kpachhai** [comment]
Closing as it looks like it's working now.
