### ISSUE TITLE
Dapp management for android

### ISSUE THREAD

**Issue by liyangwood** [cyber-republic/elastos-ReactNative-framework#23]
**Why**: user could load dapp from local or remote server. RN app need cache the dapp and check the hash for each dapp to further validation.

**Comment by liyangwood** [comment]
user could load dapp from local or remote server.
RN app need cache the dapp and check the hash for each dapp to further validation.

**Comment by kpachhai** [comment]
@liyangwood Are we planning on getting this out by alpha? If not, we can close this for now and come back to it when we have our beta planning later next month.

**Comment by liyangwood** [comment]
close it firstly
