### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by tomsej** [cyber-republic/elastos-ReactNative-framework#24]
**What**: Creating a Dockerfile to run this project in Docker container.
**Why:** For simplier starting and developing the framework.

**Comment by liyangwood** [comment]
@tomsej Hi, this is a mobile project which will build to the apk and ipa file for android and iOS. so is it available for make the whole build process in docker instance?

**Comment by tomsej** [comment]
Yeah you are right. It is usually good to have docker container for backend api. Since we do not need this I am closing this issue. Thanks a lot @liyangwood
