### ISSUE TITLE
Test cases for Carrier endpoints

### ISSUE THREAD

**Issue by tomsej** [cyber-republic/elastos-ReactNative-framework#29]

**Comment by ademcan** [comment]
Jest looks like a good library for React-Native app testing (https://jestjs.io/docs/en/tutorial-react-native.html). Testing is really important, I guess we can have someone dedicated only to that task.

**Comment by tomsej** [comment]
@ademcan do you think you could write a short info on how to make a test case?

**Comment by liyangwood** [comment]
For my knowledge, Jest is running on desktop. do you have a idea to make it running on device.

**Comment by ademcan** [comment]
I never used Jest, only mochajs for some JS testing. 
What do you mean by it runs on desktop? It seems that the Jest tests are included in the RN code so it will run in the mobile app (?).

**Comment by kpachhai** [comment]
Moving to https://github.com/cyber-republic/react-native-elastos-carrier/issues/3
