### ISSUE TITLE
build Elastos Carrier RN plugin

### ISSUE THREAD

**Issue by liyangwood** [cyber-republic/elastos-ReactNative-framework#3]

**Comment by liyangwood** [comment]
Launch for first part.
https://github.com/cyber-republic/elastos-ReactNative-framework/blob/master/doc/carrier_plugin_api.md

**Comment by kpachhai** [comment]
Please close the issue if done. Also, make sure to create new github issue for each small feature you plan to work on. This will help further keep track of each commit that goes into master branch. We don't want to be in the habit of creating one github issue per project. Instead, there should be new github issue for each new feature or functionality, bug fixes, improvements, etc. This will help further in tracking which commit went into effect at what point in time so this will help in debugging further down the road.
