### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by tomsej** [cyber-republic/elastos-ReactNative-framework#31]

**Comment by ademcan** [comment]
I have some issues at the moment with my brew installation to build the API doc for https://github.com/elastos/Elastos.ORG.Wallet.Lib.C but I guess it would make sense to build the doc and put it online accessible via a simple URL.

**Comment by kpachhai** [comment]
Is the work on this issue started yet? @JoshuaMudgett, I remember you mentioning you were working with @tomsej on this. Just wanted to know.

**Comment by andersalm** [comment]
Will be treated under https://github.com/cyber-republic/elastos-ReactNative-framework/issues/53
