### ISSUE TITLE
A problem occurred evaluating root project 'ELASTOS_RN_FRAMEWORK'.

### ISSUE THREAD

**Issue by Andrianina007** [cyber-republic/elastos-ReactNative-framework#33]
When running **react-native run-android** got an error : 

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file '/home/andrianina/project/wau/elastos-ReactNative-framework/android/build.gradle' line: 6
> 
> * What went wrong:
> A problem occurred evaluating root project 'ELASTOS_RN_FRAMEWORK'.
> > Could not find method google() for arguments [] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

**Comment by tomsej** [comment]
@Andrianina007 did you go through all steps in README.md?

**Comment by Andrianina007** [comment]
I already fix it before you notice about the carrier-plugin branch. I was starting from the master branch

**Comment by tomsej** [comment]
Thank you guys. Closing this
