### ISSUE TITLE
Build carrier aar to support x86 platform

### ISSUE THREAD

**Issue by liyangwood** [cyber-republic/elastos-ReactNative-framework#34]
**what** : build carrier android sdk to support x86.
**why :** easy to run app in android x86 simulator.

**Comment by liyangwood** [comment]
what : build carrier android sdk to support x86.
why :  easy to run app in android x86 simulator.

**Comment by liyangwood** [comment]
Looks like the build is not worked for x86. still woking on it.

**Comment by liyangwood** [comment]
it worked now.

**Comment by kpachhai** [comment]
Closing this issue. A new github issue has been created at https://github.com/cyber-republic/react-native-elastos-carrier/issues/2
