### ISSUE TITLE
Implement Javascript <-> C bridges for the API functions

### ISSUE THREAD

**Issue by ademcan** [cyber-republic/elastos-ReactNative-framework#35]
We already have a working version of the wallet C library for iOS (see wallet-plugin branch). However, this is limited to a few functions at the moment. I will take care of implementing the JS <-> C bridges for all the functions listed on https://elastoswalletlibc.readthedocs.io/en/latest/api_guide.html#apis.

For example, if we consider the getSinglePublicKey() function, one will be able to:
1. call the getSinglePublicKey() function directly from the React-Native app (using JavaScript) and 
2. have access to the getSinglePublicKey() function's returned object within the React-Native app (in JavaScript)

**Comment by tomsej** [comment]
@ademcan do you want me to split this issue to multiple tasks? Like I did it for wallet android.

**Comment by EricDualc** [comment]
@ademcan please check following commits
https://github.com/cyber-republic/elastos-ReactNative-framework/commit/fdd36d3b5a3163dcbb76b598b542480f2e77cdab
https://github.com/cyber-republic/elastos-ReactNative-framework/commit/1c87e2b2ab741a510c4fbee4422ee47cd97b16fd
or check my working branch - eric_wallet_android
I implemented Javascript <-> C bridges for the API functions. Of course for wallet plugin for android, not ios. I hope it would be helpful for you.

**Comment by ademcan** [comment]
Looks really good @EricDualc 👍 
Can you add some explanations to the commits so that everybody knows what you did. 
I just have one concern regarding the JNI libraries that you refer to. Is there a way to simply import directly from the main repo (https://github.com/elastos/Elastos.ORG.Wallet.Lib.JNI) instead of copying all the files over? This was, in case of any change on the JNI we won't need to copy all the files again.

**Comment by EricDualc** [comment]
Not sure if it is possible. If it is possible, it would be great.
Do you have any idea to implement it?

**Comment by ademcan** [comment]
I also don't know if it is possible, I mentioned it more as a potential improvement.
Maybe someone else in the group might be of help (again, if it is possible)...

**Comment by kpachhai** [comment]
If this is done, let's close it @ademcan. If there's more work to be done, let's create a corresponding issue at https://github.com/cyber-republic/react-native-elastos-wallet-core and close this issue.

**Comment by ademcan** [comment]
Agree
