### ISSUE TITLE
Create a wallet (generate mnemonic and private key)

### ISSUE THREAD

**Issue by tomsej** [cyber-republic/elastos-ReactNative-framework#36]
**Why**: creating a wallet is the first and the most basic part of wallet functionality.
**What**: user should be able to create wallet by mnemonic and private key

https://github.com/elastos/Elastos.ORG.Wallet.Lib.Android

**Comment by EricDualc** [comment]
@tomsej This was done on my working branch - eric_wallet_android.

**Comment by kpachhai** [comment]
@EricDualc Please create the corresponding issue at https://github.com/cyber-republic/react-native-elastos-wallet-core and then move the code to that repo as well. And then let's close this github issue.

**Comment by EricDualc** [comment]
ok
