### ISSUE TITLE
Import/export wallet (private key, mnemonic)

### ISSUE THREAD

**Issue by tomsej** [cyber-republic/elastos-ReactNative-framework#38]
**Why**: exporting and importing wallet is the first and the most basic part of wallet functionality.
**What**: user should be able import or export wallet throught private key and mnemonic

https://github.com/elastos/Elastos.ORG.Wallet.Lib.Android

**Comment by kpachhai** [comment]
Moved the issue to https://github.com/cyber-republic/react-native-elastos-wallet-core/issues/5
