### ISSUE TITLE
Working with addresses (create, balance)

### ISSUE THREAD

**Issue by tomsej** [cyber-republic/elastos-ReactNative-framework#39]
**Why**: wallet address is the most basic part of wallet functionality.
**What**: user should be able to create addresses, delete them and get ballance

https://github.com/elastos/Elastos.ORG.Wallet.Lib.Android

**Comment by kpachhai** [comment]
Moved the issue to https://github.com/cyber-republic/react-native-elastos-wallet-core/issues/4
