### ISSUE TITLE
Send transactions on testnet

### ISSUE THREAD

**Issue by tomsej** [cyber-republic/elastos-ReactNative-framework#40]
**Why**: transaction is the most basic part of wallet functionality.
**What**: user should be able to create new transaction and send it

Android wallet repository https://github.com/elastos/Elastos.ORG.Wallet.Lib.Android

Todo
 - [ ] Send transactions on testnet

**Comment by kpachhai** [comment]
@JoshuaMudgett Are you working on this? We're moving all the github issues to their respective github repos. If you are, please close this and open a github issue in one of the following repos:
- https://github.com/cyber-republic/react-native-elastos-wallet-core
- https://github.com/cyber-republic/react-native-elastos-carrier
