### ISSUE TITLE
Update README.md with how the directory structure is laid out

### ISSUE THREAD

**Issue by kpachhai** [cyber-republic/elastos-ReactNative-framework#46]
At the moment, it's very hard to know which directory contains what info for what purpose, eg. CR, bin, android. We need to update README.md with the most up to date directory structure, what they contain and where they're used.

**Comment by kpachhai** [comment]
@liyangwood Is this done?

**Comment by ademcan** [comment]
I guess this should be fixed by the new organization of the project (different repo for different plugins), wouldn't it?

**Comment by kpachhai** [comment]
This is true. @JoshuaMudgett is working on the Onboarding guide for each repo as well.
