### ISSUE TITLE
Create separate repositories for the different projects

### ISSUE THREAD

**Issue by ademcan** [cyber-republic/elastos-ReactNative-framework#47]
We are working on 6 different projects (carrier, wallet and DID) for iOS and Android separately. However, there is only a single repository. 
I propose that we create different repositories for the different projects, or at least 3 repos for the 3 main parts (we can put iOS and Android code together on the same repo).

**Comment by kpachhai** [comment]
Is the goal to eventually combine them all together or continue keeping them separate?

**Comment by ademcan** [comment]
I guess we could keep them separate (as it is done for the APIs). We can have 3 repositories as follow:
- react-native-elastos-carrier
- react-native-elastos-wallet
- react-native-elastos-did
Only the iOS and Android code related to the different services (carrier, wallet or did) will be present in the repositories, no dapps.
In the end we will create 3 separate npm packages for the different projects and devs can easily install them via the npm command. 
If a project needs wallet *and* carrier then the dev could simply install both of the packages.
Does it make sense?

**Comment by kpachhai** [comment]
One thing to keep in mind is that we will be disabling http/https via our custom react native framework. So, when devs wanna use our framework to build dapps, they can only interact with elastos carrier and should not have access to the network sockets as this is one of the core features that elastos wants to push. Would this be possible with different npm packages?

**Comment by ademcan** [comment]
I guess this should not be a problem. I usually end up using a lot of different npm packages on my RN apps for various parts of the app (UI, functionnality...). Once the packages are installed by the dev, there is no more need to connect via http/https if the package itself do not contains such calls.

**Comment by liyangwood** [comment]
Separate the different npm package for each plugin is the goal for next version. not current.

**Comment by liyangwood** [comment]
And Wallet and DID could combine to one npm package.

**Comment by kpachhai** [comment]
Two new repos have been created:
- https://github.com/cyber-republic/react-native-elastos-wallet-core(contains wallet features + DID)
- https://github.com/cyber-republic/react-native-elastos-carrier(contains carrier functionality)

The repo at https://github.com/cyber-republic/elastos-ReactNative-framework will be used as a framework repo that contains all the features and will be used as a dev environment for others to build their dapps on that also has http/https disabled.
