### ISSUE TITLE
Alpha Documentation

### ISSUE THREAD

**Issue by andersalm** [cyber-republic/elastos-ReactNative-framework#53]
**Who:** Developers that are; onboarding, learning, reading [Cyber Republic Developer Docs](http://staging-docs.cyberrepublic.org/#/rn-fw/), or using code related to Elastos React Native Framwork

**What:** Files in [doc folder](https://github.com/cyber-republic/elastos-ReactNative-framework/tree/master/doc) which also will be available in [Cyber Republic Developer Docs](http://staging-docs.cyberrepublic.org/#/rn-fw/)

**Why:** Make it easier to understand and use the framework

Illustrations and diagrams within docs :+1:

Important:
 - [ ] [Block Diagram](https://github.com/cyber-republic/elastos-ReactNative-framework/issues/54) - Adem
 - [ ] [Carrier service (purpose/library/API/example)](https://github.com/cyber-republic/react-native-elastos-carrier/blob/master/README.md)  - Jackie
 - [ ] [Wallet service (purpose/library/API/example)](https://github.com/cyber-republic/react-native-elastos-wallet-core/blob/master/README.md) - [Issue](https://github.com/cyber-republic/react-native-elastos-wallet-core/issues/24) - Adem / Eric

**Comment by ademcan** [comment]
Hi @aredshaw, thank you for proposing your help. Feel free to ask any question related to the project here or on Discord (https://discordapp.com/invite/MHSUVZN) channel #react-native-development

**Comment by andersalm** [comment]
Hi @aredshaw, are you still able to help and did you join discord?

@ademcan the npm install instructions are out of date for wallet core readme, can you add the intructions on how to install from github (the workaround)?

@liyangwood in the carrier documentation there seem to be a distiction between address and userid/friendid. what are the differences between the two? ("userId is friend node userId, not address.")
this could be useful for the documentation.

**Comment by ademcan** [comment]
What do you mean by the "npm install instructions"? 

The github path solution is actually "implemented" in the package.json of the demo repository, the idea is to give a path instead of a verion number for an npm package: https://github.com/ademcan/react-native-elastos-wallet-core-demo/blob/9063adb95cd187b5d62faacee52e4203db9e6dc0/package.json#L12

However, I will remove the "Additional configurations" part from the wallet-core repo as it is not necessary anymore (it was for the C library).

**Comment by andersalm** [comment]
Oh right, my bad. I didnt look at the package.json and thought there were more steps needed. Nevermind :)
