### ISSUE TITLE
Block Diagram For Modules And Libraries

### ISSUE THREAD

**Issue by andersalm** [cyber-republic/elastos-ReactNative-framework#54]
Who: Developers and people who want to understand how Elastos dapps works
What: A block diagram over how the different modules and libraries works and relate to each other
Why: To get a better understanding and see it visually

Example:
RN Wallet Core <-> CPP  <-> other library

Estimated time left: 3 hours

**Comment by andersalm** [comment]
Thanks @ademcan 
A concrete example could be useful; like showing the process on how to get from native SDK to the getBalance function in the wallet demo app, including links to repositories, explanation in text and code snippets.

**Comment by ademcan** [comment]
Here is a more detailed graphic:
![elastosbridgegraphic](https://user-images.githubusercontent.com/1199588/50546479-92a4a680-0c28-11e9-9d5d-dd40b09c226f.jpg)

**Comment by andersalm** [comment]
This is great, thank you

**Comment by andersalm** [comment]
Created a PDF file and PR

https://github.com/cyber-republic/elastos-ReactNative-framework/pull/57
